# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'
  require 'org/mapdb/elsa/3.0.0-M5/elsa-3.0.0-M5.jar'
  require 'com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar'
  require 'org/checkerframework/checker-qual/2.10.0/checker-qual-2.10.0.jar'
  require 'org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar'
  require 'com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar'
  require 'org/mapdb/mapdb/3.0.8/mapdb-3.0.8.jar'
  require 'org/eclipse/collections/eclipse-collections-forkjoin/10.2.0.M1/eclipse-collections-forkjoin-10.2.0.M1.jar'
  require 'com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar'
  require 'com/google/guava/guava/28.2-jre/guava-28.2-jre.jar'
  require 'org/eclipse/collections/eclipse-collections/10.2.0.M1/eclipse-collections-10.2.0.M1.jar'
  require 'com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar'
  require 'net/jpountz/lz4/lz4/1.3.0/lz4-1.3.0.jar'
  require 'org/eclipse/collections/eclipse-collections-api/10.2.0.M1/eclipse-collections-api-10.2.0.M1.jar'
  require 'org/jetbrains/kotlin/kotlin-stdlib-common/1.2.71/kotlin-stdlib-common-1.2.71.jar'
  require 'org/jetbrains/annotations/13.0/annotations-13.0.jar'
end

if defined? Jars
  require_jar 'com.google.code.findbugs', 'jsr305', '3.0.2'
  require_jar 'org.mapdb', 'elsa', '3.0.0-M5'
  require_jar 'com.google.guava', 'failureaccess', '1.0.1'
  require_jar 'org.checkerframework', 'checker-qual', '2.10.0'
  require_jar 'org.jetbrains.kotlin', 'kotlin-stdlib', '1.2.71'
  require_jar 'com.google.guava', 'listenablefuture', '9999.0-empty-to-avoid-conflict-with-guava'
  require_jar 'org.mapdb', 'mapdb', '3.0.8'
  require_jar 'org.eclipse.collections', 'eclipse-collections-forkjoin', '10.2.0.M1'
  require_jar 'com.google.errorprone', 'error_prone_annotations', '2.3.4'
  require_jar 'com.google.guava', 'guava', '28.2-jre'
  require_jar 'org.eclipse.collections', 'eclipse-collections', '10.2.0.M1'
  require_jar 'com.google.j2objc', 'j2objc-annotations', '1.3'
  require_jar 'net.jpountz.lz4', 'lz4', '1.3.0'
  require_jar 'org.eclipse.collections', 'eclipse-collections-api', '10.2.0.M1'
  require_jar 'org.jetbrains.kotlin', 'kotlin-stdlib-common', '1.2.71'
  require_jar 'org.jetbrains', 'annotations', '13.0'
end
